Cni rework
quortex/terraform-aws-eks-cluster pull request #60
Opened 2024-04-10 16:03 UTC by nerahou

2024-04-11 07:09 UTC, antonincms requested changes

2024-04-11 07:09 UTC, antonincms commented on versions.tf
> +    }
Provider does not seem to be used

2024-04-11 07:09 UTC, antonincms commented on main.tf
> +
```suggestion
```

2024-04-11 07:09 UTC, antonincms commented on main.tf
> +
```suggestion
```

2024-04-11 10:08 UTC, vincentmrg commented on values.yaml
This file should probably be renamed and moved to a "templates" directory.

2024-04-16 15:34 UTC, vincentmrg commented on node_group_advanced.tf
> +      } : {},
I think that this is not the label we expect.

2024-04-16 15:37 UTC, vincentmrg commented on main.tf
> +    } : {},
You should probably check if your `handle_eni_configs` variable is `true` here.

2024-04-16 15:37 UTC, vincentmrg commented on main.tf
> +    } : {},
You should probably check if your `handle_eni_configs` variable is `true` here.

2024-04-16 15:37 UTC, vincentmrg commented on node_group_advanced.tf
> +                  } : {},
You should probably check if your `handle_eni_configs` variable is `true` here.

2024-04-16 15:40 UTC, vincentmrg commented on variables.tf
> +  default     = true
By setting`false` as default value, we would be backward compatible.

2024-04-16 15:44 UTC, vincentmrg commented on node_group_advanced.tf
> +}
duplicate with the previous one

2024-04-17 07:33 UTC, vincentmrg commented on main.tf
> +    { for key, node_group in var.node_groups_advanced : key => lookup(node_group, "subnet_ids", [])[0] },
What if there's node_groups and node_groups_advanced with the same key ?

2024-04-17 07:34 UTC, vincentmrg commented on main.tf
> +    { for key, node_group in var.node_groups_advanced : key => lookup(node_group, "subnet_ids", [])[0] },
There's also a clear risk of index out-of-bounds here.

2024-04-17 07:38 UTC, vincentmrg commented on main.tf
> +  distinct_subnet_ids = distinct([for key, subnet in local.nodes_subnet_ids_map : subnet])
A bit complicated for something that could have been written `toset(values(local.nodes_subnet_ids_map))`

2024-04-17 16:18 UTC, vincentmrg approved these changes

2024-04-17 16:57 UTC, merged